let headlineNew = new Vue({
    el:'.headlineNew',
    data:{
        url:'javascript:;',
        newTitle:'习近平：积极推进我国应急管理体系和能力现代化'
    }
})
let indexBanner = new Vue({
    el:'.indexBanner',
    data:{
        indexBanner:[
            {
                url:'images/banner.png',
                info:'共中央政治局11月29日下午就我国应急管理体系...'
            },
            {
                url:'images/banner2.png',
                info:'新时代 新气象 新作为|聆听新时代的中国声音计提不充分的问题进行了认真梳理特别是对分'
            },
            {
                url:'images/banner.png',
                info:'共中央政治局11月29日下午就我国应急管理体系...'
            },
            {
                url:'images/banner2.png',
                info:'新时代 新气象 新作为|聆听新时代的中国声音计提不充分的问题进行了认真梳理特别是对分'
            },
        ]
    },
})
let indexSec01 = new Vue({
    el:'.indexSec01',
    data:{
        titleName:{
            titName01:'安全动态',
            titName02:'热点推荐'
        },
        safeHotNew:{
            imgUrl:'images/01.png',
            newTit:'四川宜宾发生一起交通事故 致3... ...',
            newIntro:'据四川省宜宾市公安局南溪区分局微信公众号发布通报，12月8日14时50分左右，南溪区宜南快速通道罗龙段发生一起交通事故。截至目前，事故造成3人死亡，另有4名伤者在医院接受救治，事故原因正在进一步调查中。截至目前事故造成3人死亡，另有4名伤者在医院接受救治，事故原因正在进一步调查中... ...    ',
            moreHref:'javascript:;'
        },
        hotRecommendsUrl:'javascript:;',
        hotRecommendsList:[
            {
                url:'javascript:;',
                title:'注册安全工程师考试交流',
                time:'2017-05-26'
            },
            {
                url:'javascript:;',
                title:'安全生产法（2014版） ',
                time:'2017-05-25'
            },
            {
                url:'javascript:;',
                title:'消防安全管理制度',
                time:'2017-05-26'
            },{
                url:'javascript:;',
                title:'清明节放假公告',
                time:'2017-03-26'
            },{
                url:'javascript:;',
                title:'注册安全工程师考试交流',
                time:'2017-05-26'
            },
            {
                url:'javascript:;',
                title:'注册安全工程师考试交流',
                time:'2017-05-26'
            },{
                url:'javascript:;',
                title:'注册安全工程师考试交流',
                time:'2017-05-26'
            },{
                url:'javascript:;',
                title:'注册安全工程师考试交流',
                time:'2017-05-26'
            },
        ]
    }
})
//indexSec02
let indexSec02 = new Vue({
    el:'.indexSec02',
    data:{
        newList:[
            {
                newUrl:'javascript:;',
                newTit:'前11月重特大生产安全事故起数同比下降16.7%',
                newTime:'12-05'
            },{
                newUrl:'javascript:;',
                newTit:'广西博白县一施工现场发生坍塌事故 致1死1伤',
                newTime:'12-05'
            },{
                newUrl:'javascript:;',
                newTit:'湖南浏阳一烟花厂发生爆炸事故造成7死13伤',
                newTime:'12-05'
            },{
                newUrl:'javascript:;',
                newTit:'用政府推广清洁煤 河北多位村民一氧化碳中毒身亡',
                newTime:'12-04'
            },
        ],
        imgList:[
            {
                imgUrl:'images/indexSec01.png',
                newHref:'javascript:;'
            },{
                imgUrl:'images/indexSec02.png',
                newHref:'javascript:;'
            },{
                imgUrl:'images/indexSec03.png',
                newHref:'javascript:;'
            },{
                imgUrl:'images/indexSec04.png',
                newHref:'javascript:;'
            }
        ],
        rightInfo:{
            safeHref:'javascript:;',
            specialHref:'javascript:;',
            specialImgUrl:'images/tebieguanzhu.png',
            specialHref01:'javascript:;',
            specialHref02:'javascript:;',
            hotHref:'javascript:;',
        }
    }
})
// indexSec03
let indexSec03 = new Vue({
    el:'.indexSec03',
    data:{
        MainTitName:[
            '特别关注',
            '培训课件',
            '应急预案',
            '安全论坛',
            '板块推荐'
        ],
        MainTitUrl:[
            'javascript:;',
            'javascript:;',
            'javascript:;',
            'javascript:;',
            'javascript:;',
        ],
        //特别关注Banner
        specialListBanner:[
            {
                imgUrl:'images/tebieBanner.png',
                imgHref:'javascript:;'
            },{
                imgUrl:'images/tebieBanner.png',
                imgHref:'javascript:;'
            }
        ],
        specialHeadList:[
            {
                intro:'新雷预警—泰安同鑫创投',
                href:'javascript:;'
            },
            {
                intro:'金融论坛开讲啦',
                href:'javascript:;'
            },
            {
                intro:'程鹤麟：马英九登太平岛 两 啊啊啊啊',
                href:'javascript:;'
            },
            {
                intro:'什么扳倒贪腐大臣？',
                href:'javascript:;'
            }
        ],
        indexSec03ListBox01:[
            {
                title:'为什么中国的体制改革变得那么困难',
                time:'01-29',
                href:'javascript:;'
            },{
                title:'08年四万亿式的发给发给大规模经济',
                time:'01-22',
                href:'javascript:;'
            },{
                title:'似懂非懂国应增加定稿对外军',
                time:'01-22',
                href:'javascript:;'
            },{
                title:'英九登的弗格森太平岛',
                time:'01-22',
                href:'javascript:;'
            },{
                title:'什么扳倒贪腐大的发送到发送到臣？',
                time:'01-22',
                href:'javascript:;'
            },{
                title:'为什么中国的体制改革变得那么困难',
                time:'01-22',
                href:'javascript:;'
            },{
                title:'08年四万亿式的发给发给大规模经济',
                time:'01-22',
                href:'javascript:;'
            },{
                title:'似懂非懂国应增加定稿对外军',
                time:'01-22',
                href:'javascript:;'
            },{
                title:'英九登的弗格森太平岛',
                time:'01-22',
                href:'javascript:;'
            },{
                title:'什么扳倒贪腐大的发送到发送到臣？',
                time:'01-22',
                href:'javascript:;'
            },
        ],
        imgUrlBox1:{
            imgSrc:'images/tebie.png',
            href:'javascript:;'
        },
        indexSec03ListBox02:[
            {
                title:'为什么中国的体制改革变得那么困难',
                time:'01-29',
                href:'javascript:;'
            },{
                title:'08年四万亿式的发给发给大规模经济',
                time:'01-22',
                href:'javascript:;'
            },{
                title:'似懂非懂国应增加定稿对外军',
                time:'01-22',
                href:'javascript:;'
            },{
                title:'英九登的弗格森太平岛',
                time:'01-22',
                href:'javascript:;'
            },{
                title:'什么扳倒贪腐大的发送到发送到臣？',
                time:'01-22',
                href:'javascript:;'
            },{
                title:'为什么中国的体制改革变得那么困难',
                time:'01-22',
                href:'javascript:;'
            },{
                title:'08年四万亿式的发给发给大规模经济',
                time:'01-22',
                href:'javascript:;'
            },{
                title:'似懂非懂国应增加定稿对外军',
                time:'01-22',
                href:'javascript:;'
            },
        ],
        indexSec03ListBox03:[
            {
                title:'为什么中国的体制改革变得那么困难',
                time:'01-29',
                href:'javascript:;'
            },{
                title:'08年四万亿式的发给发给大规模经济',
                time:'01-22',
                href:'javascript:;'
            },{
                title:'似懂非懂国应增加定稿对外军',
                time:'01-22',
                href:'javascript:;'
            },{
                title:'英九登的弗格森太平岛',
                time:'01-22',
                href:'javascript:;'
            },{
                title:'什么扳倒贪腐大的发送到发送到臣？',
                time:'01-22',
                href:'javascript:;'
            },{
                title:'为什么中国的体制改革变得那么困难',
                time:'01-22',
                href:'javascript:;'
            },{
                title:'08年四万亿式的发给发给大规模经济',
                time:'01-22',
                href:'javascript:;'
            },{
                title:'似懂非懂国应增加定稿对外军',
                time:'01-22',
                href:'javascript:;'
            },
        ],
        indexSec03ListBox04:[
            {
                title:'似懂非懂国应增加定',
                visits:'2358',
                href:'javascript:;'
            },{
                title:'英九登的弗',
                visits:'2158',
                href:'javascript:;'
            },{
                title:'什么扳倒贪腐大',
                visits:'2058',
                href:'javascript:;'
            },{
                title:'08年四万亿式的发给',
                visits:'2358',
                href:'javascript:;'
            },{
                title:'似懂非懂国应增加定',
                visits:'2358',
                href:'javascript:;'
            },{
                title:'什么扳倒贪腐大',
                visits:'2845',
                href:'javascript:;'
            },{
                title:'08年四万亿式的发给',
                visits:'221',
                href:'javascript:;'
            },{
                title:'什么扳倒贪腐大',
                visits:'208',
                href:'javascript:;'
            },{
                title:'08年四万亿式的发给',
                visits:'23',
                href:'javascript:;'
            },{
                title:'什么扳倒贪腐大',
                visits:'2358',
                href:'javascript:;'
            },{
                title:'似懂非懂国应增加定',
                visits:'2358',
                href:'javascript:;'
            },
        ],
        indexSec03Box05MenuList:[
            {
                name:'安全新闻',
                href:'javascript:;'
            },
            {
                name:'安全教育',
                href:'javascript:;'
            },{
                name:'管理体系',
                href:'javascript:;'
            },{
                name:'安全法规',
                href:'javascript:;'
            },{
                name:'安全管理',
                href:'javascript:;'
            },{
                name:'应急预案',
                href:'javascript:;'
            },{
                name:'应急预案',
                href:'javascript:;'
            },{
                name:'应急预案',
                href:'javascript:;'
            },
        ]
    }
})
let indexSec04 = new Vue({
    el:'.indexSec04',
    data:{
            leftBox:{
            boxName:'职业卫生',
            boxHref:'javascript:;',
            dataList:[
                {
                    title:'接连遭恶意冒名 陆金所雇个人尺前海理想【谨明】',
                    href:'javascript:;'
                },{
                    title:'[质疑] 接连遭恶意冒、前海理想  二哥对',
                    href:'javascript:;'
                },
                {
                    title:'接连遭恶意冒名 陆金所雇个人尺前海理想【谨明】',
                    href:'javascript:;'
                },{
                    title:'[质疑] 接连遭恶意冒、前海理想  二哥对',
                    href:'javascript:;'
                },{
                    title:'接连遭恶意冒名 陆金所雇个人尺前海理想【谨明】',
                    href:'javascript:;'
                },
            ]
        },
        centerBox:{
            boxName:'管理体系',
            boxHref:'javascript:;',
            dataList:[
                {
                    title:'[山东] 2016-02-02 金融贷 山东木木金融科技有限公司',
                    href:'javascript:;'
                },{
                    title:'[山东] 2016-02-02 金融贷 山东木木金融科技有限公司',
                    href:'javascript:;'
                },
                {
                    title:'[山东] 2016-02-02 金融贷 山东木木金融科技有限公司',
                    href:'javascript:;'
                },{
                    title:'[山东] 2016-02-02 金融贷 山东木木金融科技有限公司',
                    href:'javascript:;'
                },{
                    title:'[山东] 2016-02-02 金融贷 山东木木金融科技有限公司',
                    href:'javascript:;'
                },
            ]
        },
        rightBox:{
            boxName:'知识问答',
            boxHref:'javascript:;',
            dataList:[
                {
                    title:'2019年消防宣传月主题是什么？',
                    href:'javascript:;'
                },{
                    title:'应急预案一年做几次',
                    href:'javascript:;'
                },
                {
                    title:'安全员考试一般去哪个网站去查？怎么报考',
                    href:'javascript:;'
                },{
                    title:'危险化学品数据查询来源？',
                    href:'javascript:;'
                },{
                    title:'安全员是技术岗位吗？',
                    href:'javascript:;'
                },
            ]
        },
    }
})
let indexSec05 = new Vue({
    el:'.indexSec05',
    data:{
        indexSec05:{
            boxName:'安全论坛',
            boxHref:'javascript:;',
            dataList:[
                {
                    title:'聘用安评环评工程师人员兼',
                    time:'12-05',
                    href:'javascript:;'
                },
                {
                    title:'管理考点汇总',
                    time:'12-05',
                    href:'javascript:;'
                },{
                    title:'闲置在手没用的还可以赚',
                    time:'12-05',
                    href:'javascript:;'
                },{
                    title:'唐山丰南4.5级地震 河北天',
                    time:'12-05',
                    href:'javascript:;'
                },{
                    title:'狂砸交通灯，黑衣暴徒害死',
                    time:'12-05',
                    href:'javascript:;'
                },{
                    title:'一渔船在厦门海域遇险翻沉',
                    time:'12-05',
                    href:'javascript:;'
                },{
                    title:'“猪事”妥了？肉价大降21',
                    time:'12-05',
                    href:'javascript:;'
                },{
                    title:'山东首例！电动二轮撞人后',
                    time:'12-05',
                    href:'javascript:;'
                },{
                    title:'山东生育险并入医保倒计时',
                    time:'12-05',
                    href:'javascript:;'
                },{
                    title:'美夏威夷一造船厂发生枪击',
                    time:'12-05',
                    href:'javascript:;'
                },
                //
                {title:'聘用安评环评工程师人员兼', time:'12-05', href:'javascript:;'}, {title:'管理考点汇总', time:'12-05', href:'javascript:;'},{title:'闲置在手没用的还可以赚', time:'12-05', href:'javascript:;'},{title:'唐山丰南4.5级地震 河北天', time:'12-05', href:'javascript:;'},{title:'狂砸交通灯，黑衣暴徒害死', time:'12-05', href:'javascript:;'},{title:'一渔船在厦门海域遇险翻沉', time:'12-05', href:'javascript:;'},{title:'“猪事”妥了？肉价大降21', time:'12-05', href:'javascript:;'},{title:'山东首例！电动二轮撞人后', time:'12-05', href:'javascript:;'},{title:'山东生育险并入医保倒计时', time:'12-05', href:'javascript:;'},{title:'美夏威夷一造船厂发生枪击', time:'12-05', href:'javascript:;'},
            ]
        }
    }
})
let indexSec06 = new Vue({
    el:'.indexSec06',
    data:{
        table01:{
            tabList:['培训课件','管理资料'],
            tabCon:[
                {
                    href:'javascript:;',
                    conListBox:[
                        {
                            href:'javascript:;',
                            title:'烟气脱白技术介绍及烧结机烟气',
                            time:'12-08'
                        },{
                            href:'javascript:;',
                            title:'燃煤工业锅炉烟气脱硫脱硝技术',
                            time:'12-08'
                        },{
                            href:'javascript:;',
                            title:'火力发电厂脱硫脱硝工艺',
                            time:'12-08'
                        },{
                            href:'javascript:;',
                            title:'酸雨形成危害与防治',
                            time:'12-08'
                        },{
                            href:'javascript:;',
                            title:'中国的高速公路雾区安全研究',
                            time:'12-08'
                        },{
                            href:'javascript:;',
                            title:'南方电网公司基建工程安全质量',
                            time:'12-08'
                        },{
                            href:'javascript:;',
                            title:'煤矿新工人入矿培训课件',
                            time:'12-08'
                        },
                    ]
                },{
                    href:'javascript:;',
                    conListBox:[
                        {
                            href:'javascript:;',
                            title:'title',
                            time:'12-08'
                        },{
                            href:'javascript:;',
                            title:'title',
                            time:'12-08'
                        },
                    ]
                },
            ],
            num:0,
        },
        table02:{
            tabList:['应急预案','工商保险'],
            tabCon:[
                {
                    href:'javascript:;',
                    conListBox:[
                        {
                            href:'javascript:;',
                            title:'烟气脱白技术介绍及烧结机烟气',
                            time:'12-08'
                        },{
                            href:'javascript:;',
                            title:'燃煤工业锅炉烟气脱硫脱硝技术',
                            time:'12-08'
                        },{
                            href:'javascript:;',
                            title:'火力发电厂脱硫脱硝工艺',
                            time:'12-08'
                        },{
                            href:'javascript:;',
                            title:'酸雨形成危害与防治',
                            time:'12-08'
                        },{
                            href:'javascript:;',
                            title:'中国的高速公路雾区安全研究',
                            time:'12-08'
                        },{
                            href:'javascript:;',
                            title:'南方电网公司基建工程安全质量',
                            time:'12-08'
                        },{
                            href:'javascript:;',
                            title:'煤矿新工人入矿培训课件',
                            time:'12-08'
                        },
                    ]
                },{
                    href:'javascript:;',
                    conListBox:[
                        {
                            href:'javascript:;',
                            title:'title',
                            time:'12-08'
                        },{
                            href:'javascript:;',
                            title:'title',
                            time:'12-08'
                        },
                    ]
                },
            ],
            num:0,
        },
        table03:{
            tabList:['培训课件','管理资料'],
            tabCon:[
                {
                    href:'javascript:;',
                    conListBox:[
                        {
                            href:'javascript:;',
                            title:'烟气脱白技术介绍及烧结机烟气',
                            time:'12-08'
                        },{
                            href:'javascript:;',
                            title:'燃煤工业锅炉烟气脱硫脱硝技术',
                            time:'12-08'
                        },{
                            href:'javascript:;',
                            title:'火力发电厂脱硫脱硝工艺',
                            time:'12-08'
                        },{
                            href:'javascript:;',
                            title:'酸雨形成危害与防治',
                            time:'12-08'
                        },{
                            href:'javascript:;',
                            title:'中国的高速公路雾区安全研究',
                            time:'12-08'
                        },{
                            href:'javascript:;',
                            title:'南方电网公司基建工程安全质量',
                            time:'12-08'
                        },{
                            href:'javascript:;',
                            title:'煤矿新工人入矿培训课件',
                            time:'12-08'
                        },
                    ]
                },{
                    href:'javascript:;',
                    conListBox:[
                        {
                            href:'javascript:;',
                            title:'title',
                            time:'12-08'
                        },{
                            href:'javascript:;',
                            title:'title',
                            time:'12-08'
                        },
                    ]
                },
            ],
            num:0,
        },
        table04:{
            tabList:['应急预案','工商保险'],
            tabCon:[
                {
                    href:'javascript:;',
                    conListBox:[
                        {
                            href:'javascript:;',
                            title:'烟气脱白技术介绍及烧结机烟气',
                            time:'12-08'
                        },{
                            href:'javascript:;',
                            title:'燃煤工业锅炉烟气脱硫脱硝技术',
                            time:'12-08'
                        },{
                            href:'javascript:;',
                            title:'火力发电厂脱硫脱硝工艺',
                            time:'12-08'
                        },{
                            href:'javascript:;',
                            title:'酸雨形成危害与防治',
                            time:'12-08'
                        },{
                            href:'javascript:;',
                            title:'中国的高速公路雾区安全研究',
                            time:'12-08'
                        },{
                            href:'javascript:;',
                            title:'南方电网公司基建工程安全质量',
                            time:'12-08'
                        },{
                            href:'javascript:;',
                            title:'煤矿新工人入矿培训课件',
                            time:'12-08'
                        },
                    ]
                },{
                    href:'javascript:;',
                    conListBox:[
                        {
                            href:'javascript:;',
                            title:'title',
                            time:'12-08'
                        },{
                            href:'javascript:;',
                            title:'title',
                            time:'12-08'
                        },
                    ]
                },
            ],
            num:0,
        },
    },
    methods:{
        tab(index){
            this.table01.num = index;
        },
        tab02(index){
            this.table02.num = index;
        },
        tab03(index){
            this.table03.num = index;
        },
        tab04(index){
            this.table04.num = index;
        }
    }
})
let indexSec07 = new Vue({
    el:'.indexSec07',
    data: {
        moreHref: 'javascript:;',
        BoxNmae:'互动',
        dataList:[
            {
                time_day:'17',
                time_month:'十二月',
                questions:'三长租房建设:发展如何? 租客权益咋保障?三长租房建设三长租房建设',
                answer:'年降电费700亿 2018“新电改”红利仍将继续释放提不充分的问题进行了认真梳理特别是对分管财务的领导同志进行约谈。'
            },{
                time_day:'8',
                time_month:'六月',
                questions:'新时代人民群众的精神文化需求?',
                answer:'用途多、安全性高 量子技术将在哪些领域大显身手充分的问题进行了认真梳理特别是对分管财务的领导同志进行约谈。'
            },{
                time_day:'12',
                time_month:'八月',
                questions:'李克强签令 修改行政法规规章程序条例?',
                answer:'为新时代中国特色社会主义发展提供宪法保障计署有关审计部门对中央企业的审计针对减资准备计提不充分财务的为新时代中国特色社会主义发展提供宪法保障。'
            },{
                time_day:'13',
                time_month:'七月',
                questions:'高铁车发车前1小时预定餐饮和特产美食啦!',
                answer:'新时代 新气象 新作为|聆听新时代的中国声音计提不充分的问题进行了认真梳理特别是对分管财务的新时代 新气象 新作为|聆听新时代的中国声音。'
            },
        ]
    }
})
let indexSec08 = new Vue({
    el:'.indexSec08',
    data:{
        boxName:'安全图库',
        dataList:[
            {
                url:'javascript:;',
                imgSrc:'images/sekuai_11.png',
                title:'漫画：安全措施'
            },{
                url:'javascript:;',
                imgSrc:'images/sekuai_11.png',
                title:'漫画：安全措施'
            },{
                url:'javascript:;',
                imgSrc:'images/sekuai_11.png',
                title:'漫画：安全措施'
            },{
                url:'javascript:;',
                imgSrc:'images/sekuai_11.png',
                title:'漫画：安全措施'
            },{
                url:'javascript:;',
                imgSrc:'images/sekuai_11.png',
                title:'漫画：安全措施'
            },{
                url:'javascript:;',
                imgSrc:'images/sekuai_11.png',
                title:'漫画：安全措施'
            },{
                url:'javascript:;',
                imgSrc:'images/sekuai_11.png',
                title:'漫画：安全措施'
            },{
                url:'javascript:;',
                imgSrc:'images/sekuai_11.png',
                title:'漫画：安全措施'
            },
        ]
    },
})